# -*- coding: utf-8 -*-
"""average.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPYz6bHvmW6IIuPlfKhnBCPd4z4LkjWl
"""

import array as arr
n=int(input("Enter the elements of array :"))
ip=arr.array("i",[])
for i in range(n):
   ip.append(int(input("Enter :")))
print(ip)
sum=0
for i in range(len(ip)):
   sum=sum+ip[i]
print("sum of array is:",sum)
print(ip)
avg =sum/n
print("Average :",avg)